//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRT
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnevnik
    {
        public int id_dnevnik { get; set; }
        public int id_majka { get; set; }
        public string naslov { get; set; }
        public string sadrzaj { get; set; }
        public System.DateTime datum_zapisa { get; set; }
    
        public virtual majka majka { get; set; }
    }
}
