//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRT
{
    using System;
    using System.Collections.Generic;
    
    public partial class doktor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public doktor()
        {
            this.majka_doktor = new HashSet<majka_doktor>();
        }
    
        public int id_doktor { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string mjesto { get; set; }
        public string adresa { get; set; }
        public string broj_telefona { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<majka_doktor> majka_doktor { get; set; }

        public override string ToString()
        {
            return ime + " " + prezime;
        }

    }
}
