//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRT
{
    using System;
    using System.Collections.Generic;
    
    public partial class majka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public majka()
        {
            this.beba = new HashSet<beba>();
            this.dnevnik = new HashSet<dnevnik>();
            this.majka_dodatak_prehrani = new HashSet<majka_dodatak_prehrani>();
            this.majka_doktor = new HashSet<majka_doktor>();
            this.trening = new HashSet<trening>();
            this.zapis_opsega = new HashSet<zapis_opsega>();
            this.zapis_tezine = new HashSet<zapis_tezine>();
        }
    
        public int id_majka { get; set; }
        public string email { get; set; }
        public string lozinka { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public int godine { get; set; }
        public string mjesto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<beba> beba { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dnevnik> dnevnik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<majka_dodatak_prehrani> majka_dodatak_prehrani { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<majka_doktor> majka_doktor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trening> trening { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zapis_opsega> zapis_opsega { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zapis_tezine> zapis_tezine { get; set; }

        public override string ToString()
        {
            return ime + " " + " " + prezime;
        }
    }
}
