//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRT
{
    using System;
    using System.Collections.Generic;
    
    public partial class majka_doktor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public majka_doktor()
        {
            this.pregled = new HashSet<pregled>();
        }
    
        public int id_majka_doktor { get; set; }
        public int id_doktor { get; set; }
        public int id_majka { get; set; }
        public System.DateTime datum_pocetak { get; set; }
        public Nullable<System.DateTime> datum_kraj { get; set; }
    
        public virtual doktor doktor { get; set; }
        public virtual majka majka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pregled> pregled { get; set; }
    }
}
