//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRT
{
    using System;
    using System.Collections.Generic;
    
    public partial class pregled
    {
        public int id_pregled { get; set; }
        public int id_majka_doktor { get; set; }
        public System.DateTime datum_pregleda { get; set; }
        public string sazetak { get; set; }
    
        public virtual majka_doktor majka_doktor { get; set; }
    }
}
