//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pregnancydbEntities : DbContext
    {
        public pregnancydbEntities()
            : base("name=pregnancydbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<beba> beba { get; set; }
        public virtual DbSet<dnevnik> dnevnik { get; set; }
        public virtual DbSet<dodatak_prehrani> dodatak_prehrani { get; set; }
        public virtual DbSet<doktor> doktor { get; set; }
        public virtual DbSet<majka> majka { get; set; }
        public virtual DbSet<majka_dodatak_prehrani> majka_dodatak_prehrani { get; set; }
        public virtual DbSet<majka_doktor> majka_doktor { get; set; }
        public virtual DbSet<pregled> pregled { get; set; }
        public virtual DbSet<trening> trening { get; set; }
        public virtual DbSet<vrsta_treninga> vrsta_treninga { get; set; }
        public virtual DbSet<zapis_opsega> zapis_opsega { get; set; }
        public virtual DbSet<zapis_tezine> zapis_tezine { get; set; }
    }
}
