//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRT
{
    using System;
    using System.Collections.Generic;
    
    public partial class trening
    {
        public int id_trening { get; set; }
        public int id_vrsta { get; set; }
        public int id_majka { get; set; }
        public System.DateTime datum { get; set; }
        public string biljeske { get; set; }
    
        public virtual majka majka { get; set; }
        public virtual vrsta_treninga vrsta_treninga { get; set; }
    }
}
