//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRT
{
    using System;
    using System.Collections.Generic;
    
    public partial class zapis_opsega
    {
        public int id_zapis_opsega { get; set; }
        public int id_majka { get; set; }
        public double opseg { get; set; }
        public System.DateTime datum_pocetak { get; set; }
        public Nullable<System.DateTime> datum_kraj { get; set; }
    
        public virtual majka majka { get; set; }
    }
}
