//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRT
{
    using System;
    using System.Collections.Generic;
    
    public partial class zapis_tezine
    {
        public int id_zapis_tezine { get; set; }
        public int id_majka { get; set; }
        public double tezina { get; set; }
        public System.DateTime datum { get; set; }
    
        public virtual majka majka { get; set; }
    }
}
